### ISSUE TITLE
Why use an IIFE here?

### ISSUE THREAD

**Issue by maanlamp** [Arash217/web-app-from-scratch-18-19#1]
https://github.com/Arash217/web-app-from-scratch-18-19/blob/5539d5a09955c2c873dd7082fdb34b9274c029a8/week1/public/js/app.js#L1

There is no specific reason to use an IIFE around a program, since it's technically an IIFE already. Is there a reason for this (modularisation later on)?

**Comment by Arash217** [comment]
Yeah, it's meant for later.

**Comment by maanlamp** [comment]
Okay, nice! 👍

Remember to _close_ issues when you're done with them. I'll close this one for you.
