### ISSUE TITLE
A named function might be better here?

### ISSUE THREAD

**Issue by joostf** [Arash217/web-app-from-scratch-18-19#2]
For readability

https://github.com/Arash217/web-app-from-scratch-18-19/blob/5539d5a09955c2c873dd7082fdb34b9274c029a8/week1/public/js/app.js#L26

**Comment by Arash217** [comment]
I was using it before, but my IDE complained about the fact that the returned promise is being ignored. So I used an anonymous arrow function as a IIFE :P

I'll change it though.
