### ISSUE TITLE
Toggle classes with element.classList

### ISSUE THREAD

**Issue by joostf** [Arash217/web-app-from-scratch-18-19#4]
So you won't interfere with possible other classes in the list

https://github.com/Arash217/web-app-from-scratch-18-19/blob/5539d5a09955c2c873dd7082fdb34b9274c029a8/week1/public/js/app.js#L15

**Comment by Arash217** [comment]
Like this?

`container.classList.toggle('country');`

**Comment by Arash217** [comment]
Fixed the issue. Thanks for the feedback 👍
